# Database
spring.datasource.url=jdbc:mysql://localhost:3306/certificate_platform
spring.datasource.username=root
spring.datasource.password=Ayush123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App name
spring.application.name=certificate-platform

# Server port
server.port=8080

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayushjoshi759@gmail.com
spring.mail.password=vhne elam qbwt quxh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.certificate.output-dir=certificates
app.base-url=http://192.168.0.191:8080

# Blockchain Config
blockchain.rpc-url=https://ethereum-sepolia-rpc.publicnode.com
blockchain.private-key=8b4bdbf8676e3003d720ee6332cd61e62136e96d84384f57a2b39e0f01764e41
blockchain.contract-address=0xC45a8CE3123bB7999C4273144C2a71D8A783bC97

app.logo.upload-dir=logos
